
export const ACTION_RUN_SAGA = '@@LRRSAGA_RUN'
export const ACTION_GET_GLOBAL_STATE = '@@LRRSAGA_GET_GLOBAL_STATE'
export const ACTION_DISPATCH_GLOBAL = '@@LRRSAGA_DISPATCH_GLOBAL'
export const ACTION_IGNORE_LOCAL = '@@LRRSAGA_IGNORE_LOCAL'

export const META_RUN_SAGA = '@@LRRSAGA_RUN'
export const META_GLOBAL_ACTION = '@@LRRSAGA_GLOBAL_ACTION'